# Generated by Django 3.0.4 on 2020-03-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.PositiveIntegerField()),
                ('position_y', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
