# Generated by Django 3.0.4 on 2020-03-21 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200321_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date_expiry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='food',
            name='date_purchased',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='food',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='food',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
