# Generated by Django 3.0.4 on 2020-03-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200321_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('FR', 'Fresh'), ('EX', 'Expiring soon')], default='FR', max_length=2),
        ),
    ]
