# Generated by Django 3.0.4 on 2020-03-21 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20200321_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='unit',
            field=models.CharField(choices=[('UN', 'UN'), ('BG', 'BG'), ('BX', 'BX'), ('CN', 'CN'), ('CA', 'CA'), ('JR', 'JR'), ('PK', 'PK'), ('GR', 'GR'), ('KG', 'KG'), ('LT', 'LT')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='food',
            name='use_before',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 19, 28, 56, 637440, tzinfo=utc)),
        ),
    ]
