# Generated by Django 3.0.4 on 2020-03-21 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200321_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='use_before',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 19, 30, 39, 416625, tzinfo=utc)),
        ),
    ]
