# Generated by Django 3.0.4 on 2020-03-21 20:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20200321_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Fresh', 'FR'), ('Expiring', 'EX')], default='Fresh', max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='unit',
            field=models.CharField(choices=[('unit(s)', 'UN'), ('bag(s)', 'BG'), ('box(s)', 'BX'), ('can(s)', 'CN'), ('carton(s)', 'CA'), ('jar(s)', 'JR'), ('package(s)', 'PK'), ('gram(s)', 'GR'), ('kilo(s)', 'KG'), ('liter(s)', 'LT')], default='unit(s)', max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='use_before',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 20, 39, 50, 357766, tzinfo=utc)),
        ),
    ]
