# Generated by Django 3.0.4 on 2020-03-21 20:43

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0012_auto_20200321_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='use_before',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 20, 43, 11, 788260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
